### ISSUE TITLE
Support for 1.9

### ISSUE THREAD

**Issue by jebr** [r-clancy/PlugMan#21]
I there already support for 1.9?

**Comment by r-clancy** [comment]
In theory, nothing should be broken with 1.9 - there have been a few comments saying there were some errors, but someone pointed out that this was a fault of Spigot and has since been fixed.

http://dev.bukkit.org/bukkit-plugins/plugman/#c395

**Comment by Subtleoliver** [comment]
There is an error in some AsyncTask you are creating: https://www.dropbox.com/s/kuhk03m89h8xmkv/Nosuchmethod.PNG?dl=0

org.bukkit.server.getOnlinePlayers() doesn't exist anymore or has been changed

**Comment by r-clancy** [comment]
Give the latest dev build a shot - http://ci.ryan-clancy.com/job/PlugMan/80/artifact/target/PlugMan.jar

The error looked to stem from the plugin Metrics, I made it use the Bukkit API directly rather than using the reflection that was present before.

**Comment by r-clancy** [comment]
This error looks to be resolved, let me know if I'm wrong and the error persists.

Closing the issue.
