### ISSUE TITLE
/plugman disable could rename the jar to WhateverPlugin.jar.disabled

### ISSUE THREAD

**Issue by jonthesquirrel** [r-clancy/PlugMan#22]
Just an idea, because I do this manually after doing `/plugman unload`. `/plugman disable` currently doesn't seem to reliably stick when I restart the server, and even if it did, there's no way to tell by looking at the files in the plugins folder.

(maybe I have disable and unload mixed up, not sure)

Anyway, the idea: `/plugman disable` could rename the jar to `WhateverPlugin.jar.disabled`, and remove the `.disabled` when enabling it.

**Comment by r-clancy** [comment]
Nothing in PlugMan is meant to be permanent - unload and disable both affect plugins temporarily until the server is restarted.

I may consider adding such behaviour in the future (perhaps with a flag on the disable command), but it wouldn't be for a while as my exam period is soon beginning.

**Comment by lasercar** [comment]
Sounds good. Thanks for clarifying. I could have a try at writing it if you want. Or I could make it a separate plugin.

**Comment by Bammerbom** [comment]
Maybe make a /plugman remove command which does this?
