### ISSUE TITLE
Reverse command lookup

### ISSUE THREAD

**Issue by lasercar** [r-clancy/PlugMan#23]
It would be useful to have a kind of reverse `/plugman usage`.

`/plugman lookup biomelist` for example would tell me that the `/biomelist` command was registered by WorldEdit.

**Comment by r-clancy** [comment]
Not a bad idea, trivial to implement as well - added with PR #24.

Jenkins build - http://ci.ryan-clancy.com/job/PlugMan/81/artifact/target/PlugMan.jar

Give that build a shot and let me know how it works. Remember to disable the updater when running dev. builds or it will pull the latest version from DBO on each restart.

**Comment by lasercar** [comment]
Awesome, it works well for most commands!
Although, it doesn't work for aliases that are registered in plugin.yml, or if the commands are registered in a way other than plugin.yml. For example: WorldEdit commands or MyCommand custom commands.

**Comment by r-clancy** [comment]
I'll take a look at the alias issue over the next day or two, should be a fairly easy fix.

The WorldEdit issue stems from them not registering their commands in the [plugin.yml](https://github.com/sk89q/WorldEdit/blob/master/worldedit-bukkit/src/main/resources/plugin.yml) and using their own dynamic command registration - not sure I want to poke around in their API and try for a fix when they're doing something non-standard.

**Comment by r-clancy** [comment]
Support for doing a lookup by registered aliases has been added with PR #25.

Jenkins Build - http://ci.ryan-clancy.com/job/PlugMan/82/artifact/target/PlugMan.jar

A little bit delayed, but I'm in the thick of exam period - give this build a shot and let me know how it works.

**Comment by r-clancy** [comment]
I'm seeing nothing wrong from the testing I've done - I've pushed this to DBO as version 2.1.0.

Closing.

**Comment by lasercar** [comment]
Yep, it works with aliased commands now! Thanks for adding it!
