### ISSUE TITLE
Updater Keeps Downloading Old Version

### ISSUE THREAD

**Issue by r-clancy** [r-clancy/PlugMan#26]
Updater appears to, at least on one server, keep downloading v2.0.8 once v2.1.0 has been released.

See http://dev.bukkit.org/bukkit-plugins/plugman/#c401

**Comment by Sikatsu** [comment]
Unfortunatly I still have this issue. It keeps downgrading, I have set it to ''Check'' but it still comments theres an update while running 2.1.0 already.

**Comment by r-clancy** [comment]
Version 2.1.1 has been pushed to DBO, let me know if the issue persists with the new version.

If so, I'll have to take a deeper look into the Updater.

**Comment by r-clancy** [comment]
Closing, haven't heard any reports of this occurring with 2.1.1.
