### ISSUE TITLE
/plugman lookup doesn't work

### ISSUE THREAD

**Issue by CitrusFruit** [r-clancy/PlugMan#27]
Just updated to the latest version of plugman via bukkit and the lookup command does not work.

Error - http://hastebin.com/ocumilucih.vbs

**Comment by r-clancy** [comment]
Can you send me a link to the specific plugin that /tpa belongs to? I'd be interested to see what its plugin.yml looks like - in my testing even plugins with a single alias had been treated as an List of Strings.

I'm not able to re-produce this on the two machines I've just tested, but try the latest build in Jenkins and see if that solves the issue - I think it should do the trick, but I'm going in blind here.

Build: http://ci.ryan-clancy.com/job/PlugMan/86/artifact/target/PlugMan.jar

Note: Unrelated, but the command shouldn't have a leading slash - I'll update the docs. to make this more clear.

**Comment by r-clancy** [comment]
Is this still occurring on version 2.1.1?

**Comment by r-clancy** [comment]
Closing this issue as it doesn't appear to be an issue anymore.
