### ISSUE TITLE
PlugMan detects the wrong "owning" plugin of command

### ISSUE THREAD

**Issue by maol3** [r-clancy/PlugMan#28]
I have both Essentials and MineverseChat installed on my server. I am trying to lookup the owning plugin of /mute, which I know belongs to MineverseChat since it overrides Essentials. However, PlugMan detects Essentials as the registrator of that command.

When I'm executing /plugman lookup mute: https://gyazo.com/b7568b5b911d2000f93bc4d8a63e9988
No errors in the console.

**Comment by r-clancy** [comment]
Thanks for pointing this out - I'll push some code this weekend that will list all the plugins that the command is registered to, not just the first.

I'll link the Jenkins build here once I've got time to make the changes.

**Comment by r-clancy** [comment]
Give this build a shot and see how it works, if a command is registered to multiple plugins, it will list them.

http://ci.ryan-clancy.com/job/PlugMan/branch/lookup-command/1/artifact/target/PlugMan.jar

**Comment by maol3** [comment]
Seems to work, nice job!

As a side note, it'd be nice if PlugMan could detect if a player is typing / in front of the command and just ignore it instead of searching for "//" as prefix.

**Comment by r-clancy** [comment]
Sure - added this in the latest build of the lookup-command branch.

http://ci.ryan-clancy.com/job/PlugMan/branch/lookup-command/2/artifact/target/PlugMan.jar

**Comment by r-clancy** [comment]
Pushed to DBO with version 2.1.1 - closing.
