### ISSUE TITLE
Plugman 1.10

### ISSUE THREAD

**Issue by MrMurfy** [r-clancy/PlugMan#31]
Hello! I would like to know when is going to be avialable the plugin 'Plugman' for the version 1.10
It would be amazing
Waiting for it
Thanks!

**Comment by r-clancy** [comment]
Is anything broken with 1.10? The APIs that PlugMan uses are very stable and don't often break on updates.

**Comment by r-clancy** [comment]
Closing this issue - everything looks fine with the latest version.
