### ISSUE TITLE
Plugman not loading correctly

### ISSUE THREAD

**Issue by bshayhoe** [r-clancy/PlugMan#33]
Hey, I restarted my server a while ago and was faced with this error:
http://pastebin.com/ywj0VDqm

I hope you can provide insight as to what has gone wrong...

~Bshay

**Comment by r-clancy** [comment]
It looks as if the formatting for the config.yml of another plugin, SpawnerShop, is what is causing an issue.

Try wrapping for value for the key 'shopname' in single quotes.

**Comment by r-clancy** [comment]
Closing this issue - please re-open if my suggestion does not fix the issue or you're having any other difficulties.
