### ISSUE TITLE
problem with residence or other plugins after /plugman reload <plugin/All>

### ISSUE THREAD

**Issue by EUcreepemineCZ** [r-clancy/PlugMan#34]
Hi, I have problem, if I use: /plugman reload PermissionsEx  so I must restart server to can use residence and to show any other plugins (plugins detsroyed after this reload), what can I do? Or is error in plugman? Thanks, Patrik

**Comment by r-clancy** [comment]
Just a note on this - the effectiveness of reloading a plugin depends on implementation of `onEnable()` and `onDisable()` of the plugin that's being reloaded. Some plugins behave well and do the proper clean-up while others don't.
