### ISSUE TITLE
Item Stacking issue

### ISSUE THREAD

**Issue by KyuubiFox** [r-clancy/PlugMan#35]
Hi im trying to narrow down an issue ive been having and am checking through all my plugins trying to figure out what may be causing it. for a while now i have been having this issue and just noticed this plugin has auto updated itself to the latest version 2.1.1(1.10) when i needed the plugin for version spigot 1.8.8 (2.0.8). It appeared to be running this whole time but im starting to wonder if it had any possible negative effects such as items not stacking properly unless i throw the stacks on the ground to combine them again. If maybe you can tell me if it possible or if you may know a solution that would be great thanks!

**Comment by r-clancy** [comment]
PlugMan doesn't do anything related to items or item stacking, so this wouldn't be the source of your issue.

Regarding the auto-updating, the latest version (2.1.1) for MC 1.10 should work fine for MC 1.8 (I released it during MC 1.8 or 1.9 and just updated the version to show compatibility). The auto-update behaviour can be disable via the config file.

This hasn't been much help in solving your item stacking issue, but at least you can rule out PlugMan in your debugging - good luck!
