### ISSUE TITLE
Invalid plugin.yml Error On Startup

### ISSUE THREAD

**Issue by InfinityAspire** [r-clancy/PlugMan#42]
Short and sweet, this error on startup
[Error](https://pastebin.com/ahB8wCTk)
Using v2.1.3 on Spigot 1.11.2

**Comment by r-clancy** [comment]
This error comes from changes to Curse's CDN and the old version of the Updater library not following re-directs properly, please download the new version manually and give that a try.

**Comment by InfinityAspire** [comment]
You keep saying download it manually, what does that mean.
Error happens using one from download
Error happens when choosing the version on Bukkit and clicking download
Error happens when using latest build from integration server
