### ISSUE TITLE
Randomly stop working??[solved]

### ISSUE THREAD

**Issue by RaveGraph** [r-clancy/PlugMan#44]
Hi there,so thing is that i run a thermos server 1.7.10 (cauldron) and i have plugman installed and when i fresh install it on my server its fully functioning.Then i go to sleep and next day i log in to my server and the server doesnt know if plugman exist,i type /plugman and it shows me the classic "type /help for help".I cant place a log because i simply dont know when it is crashing/stoping!If you have any ideas on what could cause this please reply here.
Thanks for your time.

**Comment by RaveGraph** [comment]
***EDIT***
I found a piece of log that may help out
https://pastebin.com/3wEU2fDp

**Comment by r-clancy** [comment]
Make sure you're running the latest version (2.1.3 - https://dev.bukkit.org/projects/plugman/files/2412148). There was an issue with 2.1.2 that caused issues when the updater ran.

**Comment by RaveGraph** [comment]
Yeah but i am running 1.7.10 will the latest version work for me?

**Comment by r-clancy** [comment]
@RaveGraph Sorry for the delay, but it should work - the APIs that PlugMan uses are very stable and tend not to change with updates.

**Comment by RaveGraph** [comment]
Yep i tested it and its working!Thanks for this awesome plugin!

**Comment by r-clancy** [comment]
Glad you got it working!

Closing issue.
