### ISSUE TITLE
Updater Logic Issue: 2.1.3 is not greater than 2.1.4 (Source)

### ISSUE THREAD

**Issue by CDAGaming** [r-clancy/PlugMan#47]
2:24:54 PM [INFO] [PlugMan] Enabling PlugMan v2.1.4
2:24:54 PM [INFO] [FarmLimiter] Enabling FarmLimiter v1.2
2:24:54 PM [INFO] UUID of player CDA_Gaming is 5c868fb2-7727-4cb8-a7d6-3083fa175063
2:24:55 PM [INFO] Done (4.302s)! For help, type "help" or "?"
2:24:55 PM [INFO] Timings Reset
2:24:55 PM [INFO] CDA_Gaming[/127.0.0.1:30761] logged in with entity id 133 at ([world]-18.224517882568847, 71.0, 263.9105573588062)
2:24:55 PM [INFO] [PlugMan] A new update has been found. Please visit "http://servermods.cursecdn.com/files/2412/148/PlugMan.jar" to download it.

**Comment by r-clancy** [comment]
Are you trying to use a development build from my Jenkins? If so, the Updater logic will always try and use the latest build that is released on DBO. You may want to consider changing the `updater-type` to `check` in PlugMan's config.

**Comment by CDAGaming** [comment]
Ok, thank you.
