### ISSUE TITLE
Error while launching PlugMan

### ISSUE THREAD

**Issue by AhRoon** [r-clancy/PlugMan#51]
Server Version: Spigot 1.8.8
OS Version: Windows 10
https://pastebin.com/GYg0M119
Can you fix this issue?
Thanks.

**Comment by r-clancy** [comment]
What version of PlugMan are you using? Try re-downloading the latest release manually and try again, there was a bug a while back with a version that had an invalid plugin.yml

**Comment by AhRoon** [comment]
I'm currently using Spigot 1.8.8.
Can you add support for Spigot 1.8.8 if the plugin doesn't support that
version?

**Comment by r-clancy** [comment]
Please delete the current PlugMan.jar and re-download from https://dev.bukkit.org/projects/plugman/files/2466685
