### ISSUE TITLE
/plugman list kicks me from the server

### ISSUE THREAD

**Issue by N0tMyFaultOG** [r-clancy/PlugMan#57]
If I type `/plugman list` I get kicked from the server and it shows me that message
![](https://i.imgur.com/upN8gAE.png) even if the server keeps online and prints this in the console
`[09:41:54 ERROR]: io.netty.handler.codec.EncoderException: String too big (was 216468 bytes encoded, max 44767)`
Running Plugman version 1.8.1 ![](https://i.imgur.com/ViCdGrz.png)

**Comment by Dart2112** [comment]
1.8.1 is incredibly old(2012 in fact), for some reason the auto-updater keeps downloading that version in place of the new one. what you need to do is redownload from Bukkit and completely reinstall. remove all plugin files. then reinstall the current version from Bukkit and disable auto updates. then delete the already downloaded update from the update folder. this will allow you to stay on the current stable version.

**Comment by N0tMyFaultOG** [comment]
#58 
Much appreciated
