### ISSUE TITLE
Supports 1.14.1?

### ISSUE THREAD

**Issue by ziemniok99** [r-clancy/PlugMan#71]
Supports 1.14.1?

**Comment by kennyrkun** [comment]
Not yet.

**Comment by r-clancy** [comment]
Is there an issue with 1.14.1? The APIs PlugMan used are remarkably stable and don't change often. Please test and let me know.

**Comment by ziemniok99** [comment]
I can't test, sorry. I didn't bought my server, I will do it in future. Right now I am making a list of plugins, and building in free server so I can use only basic plugins like WorldEdit. Again Sorry.

**Comment by Vencorr** [comment]
Been using plugman just fine on 1.14.1, no issues I've known that isn't related to the plugin having trouble, but that's just normal stuff.

**Comment by r-clancy** [comment]
Closing as it seems to work fine with 1.14.1.
