### ISSUE TITLE
Critical Vulnerability

### ISSUE THREAD

**Issue by GitClo** [r-clancy/PlugMan#74]
If player type /plugins he dont have permission.
But if someone type /plugins 1 it gives all plugin list to him!!
I need to fix it.
Sorry, if this is my mistake.

**Comment by Macil** [comment]
The plugins command is implemented by Bukkit/Spigot itself, not PlugMan.

**Comment by r-clancy** [comment]
Closing this - as @Macil said, this isn't handled by PlugMan.
