### ISSUE TITLE
wrong default path in plugin.xml 

### ISSUE THREAD

**Issue by felaray** [r-clancy/PlugMan#79]
I'm using Plugman to create a simple plugin.
But unable to compile success in Android.

The reason is in **plugin.file**

> Default plugin.xml 

`<?xml version='1.0' encoding='utf-8'?>
<plugin id="SimpleMath" version="1.0.0" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android"><name>MyMath</name><js-module name="MyMath" src="www/MyMath.js"><clobbers target="cordova.plugins.MyMath" /></js-module><platform name="android"><config-file parent="/*" target="res/xml/config.xml"><feature name="MyMath"><param name="android-package" value="SimpleMath.MyMath" /></feature></config-file><config-file parent="/*" target="AndroidManifest.xml"></config-file><source-file src="src/android/MyMath.java" target-dir="src/SimpleMath/MyMath" /></platform></plugin>
`

> Fixing plugin.xml (edit target-dir)

`<?xml version='1.0' encoding='utf-8'?>
<plugin id="SimpleMath" version="1.0.0" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android"><name>MyMath</name><js-module name="MyMath" src="www/MyMath.js"><clobbers target="cordova.plugins.MyMath" /></js-module><platform name="android"><config-file parent="/*" target="res/xml/config.xml"><feature name="MyMath"><param name="android-package" value="SimpleMath.MyMath" /></feature></config-file><config-file parent="/*" target="AndroidManifest.xml"></config-file><source-file src="src/android/MyMath.java" **target-dir="src/SimpleMath**" /></platform></plugin>`

**Comment by r-clancy** [comment]
Wrong plugman - https://github.com/apache/cordova-plugman
